# This file was generated by GoReleaser. DO NOT EDIT.
cask "stratl" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "3bfe02ce2eb5306301e9c090e1c3089b5fc7482e04cfc5db2e02f076996bafa3"
      url "https://github.com/Metricall-AI-Lab/stratl-releases/releases/download/v#{version}/stratl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "88dda32bd8d4e91d9247953d3eafd139b2993097cf4e34653cee517ac2de8577"
      url "https://github.com/Metricall-AI-Lab/stratl-releases/releases/download/v#{version}/stratl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "324b3cfc8330af85827dddd8f3d57848c22b222ecf3dbf74d21c4b4ec190f743"
      url "https://github.com/Metricall-AI-Lab/stratl-releases/releases/download/v#{version}/stratl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba1068a4655845801978cad7bf832911a10871597b4cfcaec2b0750b05a9b4ad"
      url "https://github.com/Metricall-AI-Lab/stratl-releases/releases/download/v#{version}/stratl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "stratl"
  desc "Offline verifier for Stratl Record Format evidence bundles"
  homepage "https://stratl.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stratl"

  # No zap stanza required
end
